services:
  bun:
    image: imbios/bun-node
    command: bun run dev
    ports:
      - ${MAPPED_PORT:-4000}:4000
    volumes:
      - ./:/home/bun/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  docs:
    image: imbios/bun-node
    command: bun run docs:dev
    ports:
      - ${MAPPED_DOCS_PORT:-5173}:5173
    volumes:
      - ./:/home/bun/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  database:
    image: postgres:16
    restart: unless-stopped
    ports:
      - ${MAPPED_DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: data_management_tool
      POSTGRES_DB: data_management_tool
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  pgdata:
