services:
  bun:
    image: imbios/bun-node
    command: bun run dev
    ports:
      - 4000:4000
    volumes:
      - ./:/home/bun/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  database:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    expose: [5432]
    environment:
      POSTGRES_USER: example
      POSTGRES_DB: main
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}'
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  pgdata:
